kernel-shark: Set the DISPLAY environment for pkexec kshark-record
When running a fresh install, I hit this:

 ERROR:  Capture process failed:
 Unknown errorqt.qpa.screen: QXcbConnection: Could not connect to display
 Could not connect to any X display.

This was due to pkexec not saving the DISPLAY environment variable. To solve
this, pass that variable as one of the environment variables to pkexec.

Link: http://lore.kernel.org/linux-trace-devel/20190723225238.859019956@goodmis.org

Reviewed-by: Yordan Karadzhov (VMware) <y.karadz@gmail.com>
Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>